<#
.SYNOPSIS
    Installs Hades for the current Windows user account.
.DESCRIPTION
    User-scope only: creates an install directory (default
    %LOCALAPPDATA%\Programs\Hades), writes hades.cmd / hades.ps1 shims into
    its bin\ subdirectory, and adds that directory to the CURRENT USER's PATH
    via [Environment]::SetEnvironmentVariable(..., 'User'). Never touches the
    machine-wide PATH, never requires (and by default refuses to run from) an
    elevated session.

    The exact decisions this script makes are mirrored, as pure/injectable
    logic, in src/hades/install/windows.ts (buildWindowsInstallPlan) -- that
    module's test suite parses these actual bytes with a real PowerShell
    tokenizer (parsePowerShellScript / auditInstallPs1) to prove this script
    really implements the contract, even on a machine with no pwsh installed.
.PARAMETER InstallDir
    Override the install directory. Defaults to $env:HADES_INSTALL_DIR, then
    %LOCALAPPDATA%\Programs\Hades.
.PARAMETER DataDir
    Override the user data directory. Defaults to $env:HADES_DATA_DIR, then
    %APPDATA%\hades, then %LOCALAPPDATA%\hades, then %USERPROFILE%\.hades.
.PARAMETER Version
    Version string recorded in the generated shims.
.PARAMETER DryRun
    Compute and print the plan; make no filesystem or PATH changes.
.PARAMETER Force
    Overwrite an already-installed shim/PATH entry (mode becomes "reinstall").
.PARAMETER Purge
    With -Uninstall, also delete the data directory. Ignored otherwise.
.PARAMETER Uninstall
    Remove the shims this installer created and the PATH entry it added.
    Never touches the data directory unless -Purge is also given.
.PARAMETER NoModifyPath
    Do everything except edit the user PATH.
.PARAMETER Json
    Print the plan as a single JSON object instead of human-readable text.
.PARAMETER Help
    Print usage and exit.
#>
[CmdletBinding()]
param(
    [Parameter()]
    [string]$InstallDir = "",

    [Parameter()]
    [string]$DataDir = "",

    [Parameter()]
    [string]$Version = "0.1.0",

    [switch]$DryRun,
    [switch]$Force,
    [switch]$Purge,
    [switch]$Uninstall,
    [switch]$NoModifyPath,
    [switch]$Json,
    [switch]$Help
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Show-Usage {
    @"
Hades Windows installer (user scope -- never touches the machine PATH)

USAGE:
  install.ps1 [-InstallDir <path>] [-DataDir <path>] [-Version <ver>]
              [-DryRun] [-Force] [-Purge] [-Uninstall] [-NoModifyPath] [-Json] [-Help]

  -InstallDir <path>   Install directory (default: HADES_INSTALL_DIR env var,
                        then %LOCALAPPDATA%\Programs\Hades)
  -DataDir <path>      Data directory (default: HADES_DATA_DIR env var, then
                        %APPDATA%\hades)
  -Version <ver>       Version string recorded in the generated shims
  -DryRun              Print the plan; make no changes
  -Force                Overwrite an existing install (mode: reinstall)
  -Purge               With -Uninstall, also delete the data directory
  -Uninstall            Remove the shims and PATH entry this installer created
  -NoModifyPath         Do everything except edit the user PATH
  -Json                 Print the plan as a single JSON object
  -Help                 Show this message
"@ | Write-Output
}

if ($Help) {
    Show-Usage
    exit 0
}

# ---------------------------------------------------------------------------
# Tiny pure helpers (kept dependency-free and mirrored in windows.ts)
# ---------------------------------------------------------------------------

function Get-NormalizedPathKey {
    param([string]$PathValue)
    $normalized = $PathValue.Trim() -replace '/', '\'
    while ($normalized.Length -gt 3 -and $normalized.EndsWith('\')) {
        $normalized = $normalized.Substring(0, $normalized.Length - 1)
    }
    return $normalized.ToLowerInvariant()
}

function Join-WinPath {
    param([string[]]$Segments)
    $clean = @()
    foreach ($segment in $Segments) {
        if ([string]::IsNullOrWhiteSpace($segment)) { continue }
        $piece = ($segment -replace '/', '\').TrimEnd('\')
        if ($piece.Length -gt 0) { $clean += $piece }
    }
    return ($clean -join '\')
}

function Get-CmdShimContent {
    param([string]$RepoRoot, [string]$Ver)
    $lines = @(
        '@echo off',
        'rem Hades user-scope shim for Windows (cmd.exe).',
        "rem Generated by install.ps1 for hades v$Ver. Do not edit by hand.",
        'setlocal',
        "node `"$RepoRoot\node_modules\tsx\dist\cli.mjs`" `"$RepoRoot\src\hades\bin\hades.ts`" %*",
        'endlocal & exit /b %ERRORLEVEL%'
    )
    return (($lines -join "`r`n") + "`r`n")
}

function Get-Ps1ShimContent {
    param([string]$RepoRoot, [string]$Ver)
    $lines = @(
        '# Hades user-scope shim for Windows (PowerShell).',
        "# Generated by install.ps1 for hades v$Ver. Do not edit by hand.",
        'param()',
        "`$ErrorActionPreference = 'Stop'",
        "& node `"$RepoRoot\node_modules\tsx\dist\cli.mjs`" `"$RepoRoot\src\hades\bin\hades.ts`" @args",
        'exit $LASTEXITCODE'
    )
    return (($lines -join "`r`n") + "`r`n")
}

# ---------------------------------------------------------------------------
# Probe host facts
# ---------------------------------------------------------------------------

$NodeVersionRaw = $null
$nodeCmd = Get-Command node -ErrorAction SilentlyContinue
if ($nodeCmd) {
    try {
        $NodeVersionRaw = (& node --version 2>$null | Select-Object -First 1)
    } catch {
        $NodeVersionRaw = $null
    }
}

$LocalAppData = $env:LOCALAPPDATA
$AppDataDir = $env:APPDATA
$UserProfileDir = $env:USERPROFILE

$IsElevatedSession = $false
try {
    $currentIdentity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $currentPrincipal = New-Object Security.Principal.WindowsPrincipal($currentIdentity)
    $IsElevatedSession = $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
} catch {
    $IsElevatedSession = $false
}

$ExecPolicy = $null
try {
    $ExecPolicy = (Get-ExecutionPolicy -Scope CurrentUser).ToString()
} catch {
    $ExecPolicy = $null
}

# ---------------------------------------------------------------------------
# Resolve target directories (explicit option > HADES_* env > LOCALAPPDATA/APPDATA)
# ---------------------------------------------------------------------------

$ResolvedInstallDir = $InstallDir
if ([string]::IsNullOrWhiteSpace($ResolvedInstallDir)) { $ResolvedInstallDir = $env:HADES_INSTALL_DIR }
if ([string]::IsNullOrWhiteSpace($ResolvedInstallDir)) {
    if (-not [string]::IsNullOrWhiteSpace($LocalAppData)) {
        $ResolvedInstallDir = Join-WinPath @($LocalAppData, 'Programs', 'Hades')
    } else {
        $ResolvedInstallDir = ''
    }
}

$ShimDir = ''
if ($ResolvedInstallDir) { $ShimDir = Join-WinPath @($ResolvedInstallDir, 'bin') }

$ResolvedDataDir = $DataDir
if ([string]::IsNullOrWhiteSpace($ResolvedDataDir)) { $ResolvedDataDir = $env:HADES_DATA_DIR }
if ([string]::IsNullOrWhiteSpace($ResolvedDataDir)) {
    if (-not [string]::IsNullOrWhiteSpace($AppDataDir)) {
        $ResolvedDataDir = Join-WinPath @($AppDataDir, 'hades')
    } elseif (-not [string]::IsNullOrWhiteSpace($LocalAppData)) {
        $ResolvedDataDir = Join-WinPath @($LocalAppData, 'hades')
    } else {
        $ResolvedDataDir = Join-WinPath @($UserProfileDir, '.hades')
    }
}

$CmdShimPath = ''
$Ps1ShimPath = ''
if ($ShimDir) {
    $CmdShimPath = Join-WinPath @($ShimDir, 'hades.cmd')
    $Ps1ShimPath = Join-WinPath @($ShimDir, 'hades.ps1')
}

# ---------------------------------------------------------------------------
# Current user PATH
# ---------------------------------------------------------------------------

$CurrentUserPath = [Environment]::GetEnvironmentVariable('Path', 'User')
$PathEntries = @()
if ($CurrentUserPath) {
    $PathEntries = @($CurrentUserPath -split ';' | Where-Object { $_ -ne '' })
}

$PathAlreadyContainsShimDir = $false
if ($ShimDir) {
    $shimKey = Get-NormalizedPathKey $ShimDir
    foreach ($entry in $PathEntries) {
        if ((Get-NormalizedPathKey $entry) -eq $shimKey) { $PathAlreadyContainsShimDir = $true; break }
    }
}

$ModifyPath = -not $NoModifyPath

# ---------------------------------------------------------------------------
# Blockers
# ---------------------------------------------------------------------------

$Blockers = @()
function Add-Blocker {
    param([string]$Code, [string]$Message, [string]$Remedy)
    $script:Blockers += [PSCustomObject]@{ code = $Code; message = $Message; remedy = $Remedy }
}

if ($IsElevatedSession -and $env:HADES_ALLOW_ELEVATED -ne '1') {
    Add-Blocker 'elevated-refused' "install.ps1 was launched from an elevated (Administrator) session" "re-run from a normal, non-elevated PowerShell/terminal window -- Hades installs only into your user profile and never needs admin rights; if you must proceed elevated, set HADES_ALLOW_ELEVATED=1 first"
}

if ($ExecPolicy -eq 'Restricted' -or $ExecPolicy -eq 'AllSigned') {
    Add-Blocker 'execution-policy' "the current PowerShell execution policy (`"$ExecPolicy`") blocks running local scripts" "run: Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned"
}

if ($Uninstall) {
    if (-not $PathAlreadyContainsShimDir) {
        Add-Blocker 'nothing-to-uninstall' "no Hades installation was found on the user PATH" "nothing to do -- if you expected an existing install, check -InstallDir/HADES_INSTALL_DIR match the values used originally"
    }
} else {
    if (-not $NodeVersionRaw) {
        Add-Blocker 'node-missing' "Node.js was not found on PATH" "install Node.js >= 20 from https://nodejs.org/ and re-run install.ps1"
    } else {
        $verText = ($NodeVersionRaw -replace '^v', '')
        $majorText = ($verText -split '\.')[0]
        $major = 0
        $parsedOk = [int]::TryParse($majorText, [ref]$major)
        if (-not $parsedOk -or $major -lt 20) {
            Add-Blocker 'node-too-old' "Node.js $NodeVersionRaw is older than the required v20" "upgrade Node.js to >= 20 and re-run install.ps1"
        }
    }

    if ([string]::IsNullOrWhiteSpace($ResolvedInstallDir)) {
        Add-Blocker 'no-local-appdata' "the %LOCALAPPDATA% environment variable is not set, so a default install directory could not be determined" "set %LOCALAPPDATA%, or pass -InstallDir <path> / set HADES_INSTALL_DIR explicitly"
    } elseif ($ResolvedInstallDir -match '^[A-Za-z]:\\(Program Files( \(x86\))?|Windows)(\\|$)' -and -not $IsElevatedSession) {
        Add-Blocker 'install-dir-not-writable' "the resolved install directory `"$ResolvedInstallDir`" is inside a system-protected location a non-elevated user cannot write to" "choose a user-writable install directory with -InstallDir <path> (default: %LOCALAPPDATA%\Programs\Hades)"
    }
}

# ---------------------------------------------------------------------------
# Mode
# ---------------------------------------------------------------------------

$Mode = 'install'
if ($Uninstall) {
    $Mode = if ($PathAlreadyContainsShimDir) { 'uninstall' } else { 'noop' }
} elseif ($PathAlreadyContainsShimDir) {
    $Mode = if ($Force) { 'reinstall' } else { 'upgrade' }
}

$Ok = ($Blockers.Count -eq 0)

# ---------------------------------------------------------------------------
# Steps + mutations (every mutating statement individually guarded by
# `if (-not $DryRun) { ... }` -- see src/hades/install/windows.ts's audit).
# ---------------------------------------------------------------------------

$Steps = New-Object System.Collections.ArrayList
function Add-Step {
    param([string]$Id, [string]$Kind, [string]$Target, [string]$Detail, [bool]$Reversible)
    [void]$script:Steps.Add([PSCustomObject]@{ id = $Id; kind = $Kind; target = $Target; detail = $Detail; reversible = $Reversible })
}

$Warnings = @()
$UserPathAfter = $PathEntries
$RepoRoot = $PSScriptRoot

if (-not $Uninstall) {
    $nodeDetail = if ($NodeVersionRaw) { "found Node.js $NodeVersionRaw" } else { "Node.js not found on PATH" }
    Add-Step 'check-node' 'check' 'node' $nodeDetail $false

    if ($ResolvedInstallDir) {
        Add-Step 'mkdir-install-dir' 'mkdir' $ResolvedInstallDir "create $ResolvedInstallDir if missing" $true
        Add-Step 'mkdir-shim-dir' 'mkdir' $ShimDir "create $ShimDir if missing" $true
        Add-Step 'mkdir-data-dir' 'mkdir' $ResolvedDataDir "create $ResolvedDataDir if missing" $false
        Add-Step 'write-cmd-shim' 'write' $CmdShimPath "write $CmdShimPath" $true
        Add-Step 'write-ps1-shim' 'write' $Ps1ShimPath "write $Ps1ShimPath" $true

        if ($ModifyPath) {
            if ($PathAlreadyContainsShimDir) {
                Add-Step 'note-path-already-present' 'note' $ShimDir "$ShimDir is already on the user PATH; no change needed" $false
            } else {
                $UserPathAfter = @($PathEntries + $ShimDir)
                Add-Step 'set-user-path-add' 'set-user-path' $ShimDir "add $ShimDir to the user PATH" $true
            }
        } else {
            Add-Step 'note-path-not-modified' 'note' $ShimDir "-NoModifyPath: PATH left untouched -- add $ShimDir to PATH manually to use the `"hades`" command" $false
        }

        if ([string]::IsNullOrWhiteSpace($AppDataDir) -and [string]::IsNullOrWhiteSpace($DataDir) -and [string]::IsNullOrWhiteSpace($env:HADES_DATA_DIR)) {
            $Warnings += "%APPDATA% is not set; using `"$ResolvedDataDir`" as a fallback data directory"
        }

        if (-not $DryRun) {
            New-Item -ItemType Directory -Force -Path $ResolvedInstallDir | Out-Null
            New-Item -ItemType Directory -Force -Path $ShimDir | Out-Null
            New-Item -ItemType Directory -Force -Path $ResolvedDataDir | Out-Null
            Set-Content -LiteralPath $CmdShimPath -Value (Get-CmdShimContent -RepoRoot $RepoRoot -Ver $Version) -NoNewline -Encoding ascii
            Set-Content -LiteralPath $Ps1ShimPath -Value (Get-Ps1ShimContent -RepoRoot $RepoRoot -Ver $Version) -NoNewline -Encoding utf8
        }
        if (-not $DryRun) {
            if ($ModifyPath -and -not $PathAlreadyContainsShimDir) {
                [Environment]::SetEnvironmentVariable('Path', ($UserPathAfter -join ';'), 'User')
            }
        }
    }
} elseif ($PathAlreadyContainsShimDir) {
    Add-Step 'remove-cmd-shim' 'remove' $CmdShimPath "remove $CmdShimPath" $true
    Add-Step 'remove-ps1-shim' 'remove' $Ps1ShimPath "remove $Ps1ShimPath" $true

    $shimKeyForRemoval = Get-NormalizedPathKey $ShimDir
    $UserPathAfter = @($PathEntries | Where-Object { (Get-NormalizedPathKey $_) -ne $shimKeyForRemoval })
    Add-Step 'set-user-path-remove' 'set-user-path' $ShimDir "remove $ShimDir from the user PATH" $true

    if ($Purge) {
        Add-Step 'remove-data-dir' 'remove' $ResolvedDataDir "-Purge: recursively remove $ResolvedDataDir" $false
    } else {
        Add-Step 'note-data-dir-preserved' 'note' $ResolvedDataDir "data under $ResolvedDataDir was left in place (pass -Purge to remove it)" $false
    }

    if (-not $DryRun) {
        if (Test-Path -LiteralPath $CmdShimPath) { Remove-Item -LiteralPath $CmdShimPath -Force -ErrorAction SilentlyContinue }
        if (Test-Path -LiteralPath $Ps1ShimPath) { Remove-Item -LiteralPath $Ps1ShimPath -Force -ErrorAction SilentlyContinue }
        [Environment]::SetEnvironmentVariable('Path', ($UserPathAfter -join ';'), 'User')
    }
    if (-not $DryRun) {
        if ($Purge) {
            Remove-Item -LiteralPath $ResolvedDataDir -Recurse -Force -ErrorAction SilentlyContinue
        }
    }
}

$JoinedPathAfter = ($UserPathAfter -join ';')
if ($JoinedPathAfter.Length -ge 1900) {
    $Warnings += "the user PATH after this change is $($JoinedPathAfter.Length) characters, close to the legacy 2048-character limit some tools still enforce -- consider trimming unused entries"
}

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------

$PlanObject = [PSCustomObject]@{
    mode                       = $Mode
    ok                         = $Ok
    version                    = $Version
    installDir                 = $ResolvedInstallDir
    shimDir                    = $ShimDir
    dataDir                    = $ResolvedDataDir
    cmdShimPath                = $CmdShimPath
    ps1ShimPath                = $Ps1ShimPath
    pathAlreadyContainsShimDir = $PathAlreadyContainsShimDir
    userPathAfter              = $UserPathAfter
    steps                      = $Steps
    blockers                   = $Blockers
    warnings                   = $Warnings
}

if ($Json) {
    $PlanObject | ConvertTo-Json -Depth 8
} else {
    Write-Output "hades windows installer -- mode: $Mode$(if (-not $Ok) { ' (blocked)' })"
    Write-Output "  version:     $Version"
    Write-Output "  install dir: $(if ($ResolvedInstallDir) { $ResolvedInstallDir } else { '(unresolved)' })"
    Write-Output "  shim dir:    $(if ($ShimDir) { $ShimDir } else { '(unresolved)' })"
    Write-Output "  data dir:    $ResolvedDataDir"

    if ($Blockers.Count -gt 0) {
        Write-Output "blockers:"
        foreach ($b in $Blockers) {
            Write-Output "  - [$($b.code)] $($b.message)"
            Write-Output "    remedy: $($b.remedy)"
        }
    }

    if ($Steps.Count -gt 0) {
        Write-Output "steps:"
        foreach ($step in $Steps) {
            Write-Output "  - ($($step.kind)) $($step.detail)"
        }
    }

    if ($Warnings.Count -gt 0) {
        Write-Output "warnings:"
        foreach ($w in $Warnings) {
            Write-Output "  - $w"
        }
    }

    if ($DryRun) { Write-Output "(dry run: no changes were made)" }
}

if (-not $Ok -and -not $DryRun) {
    exit 1
}
exit 0
