import type { AgentsMdConfig, SkillMarkdown, CodexTomlConfig } from "./types";

/**
 * Generate an AGENTS.md file in Markdown format from the given config.
 */
export function generateAgentsMd(config: AgentsMdConfig): string {
  const lines: string[] = [];

  lines.push(`# ${config.name}`);
  lines.push("");
  lines.push(config.description);
  lines.push("");

  // Configuration section — only emit fields that are present
  lines.push("## Configuration");
  lines.push("");
  if (config.model !== undefined) {
    lines.push(`- **Model**: ${config.model}`);
  }
  if (config.version !== undefined) {
    lines.push(`- **Version**: ${config.version}`);
  }
  if (config.autonomy !== undefined) {
    lines.push(`- **Autonomy**: ${config.autonomy}`);
  }
  if (config.maxTurns !== undefined) {
    lines.push(`- **Max Turns**: ${config.maxTurns}`);
  }
  lines.push("");

  // Skills
  if (config.skills && config.skills.length > 0) {
    lines.push("## Skills");
    lines.push("");
    for (const skill of config.skills) {
      lines.push(`- ${skill}`);
    }
    lines.push("");
  }

  // Tools
  if (config.tools && config.tools.length > 0) {
    lines.push("## Tools");
    lines.push("");
    for (const tool of config.tools) {
      lines.push(`- ${tool}`);
    }
    lines.push("");
  }

  // System Prompt
  if (config.systemPrompt !== undefined) {
    lines.push("## System Prompt");
    lines.push("");
    lines.push(config.systemPrompt);
    lines.push("");
  }

  // Approval Required
  if (config.requireApprovalFor && config.requireApprovalFor.length > 0) {
    lines.push("## Approval Required");
    lines.push("");
    for (const item of config.requireApprovalFor) {
      lines.push(`- ${item}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by @agent-harness/core/codex*");

  return lines.join("\n");
}

/**
 * Generate a skill reference document in Markdown format.
 */
export function generateSkillMarkdown(skill: SkillMarkdown): string {
  const lines: string[] = [];

  lines.push(`# Skill: ${skill.name}`);
  lines.push("");
  lines.push(skill.description);
  lines.push("");

  lines.push("## Usage");
  lines.push("");
  lines.push(skill.usage);
  lines.push("");

  // Parameters table
  if (skill.parameters && skill.parameters.length > 0) {
    lines.push("## Parameters");
    lines.push("");
    lines.push("| Name | Type | Required | Description |");
    lines.push("|------|------|----------|-------------|");
    for (const param of skill.parameters) {
      const required = param.required ? "Yes" : "No";
      lines.push(`| ${param.name} | ${param.type} | ${required} | ${param.description} |`);
    }
    lines.push("");
  }

  // Tools Used
  if (skill.tools.length > 0) {
    lines.push("## Tools Used");
    lines.push("");
    for (const tool of skill.tools) {
      lines.push(`- ${tool}`);
    }
    lines.push("");
  }

  // Examples
  if (skill.examples.length > 0) {
    lines.push("## Examples");
    lines.push("");
    skill.examples.forEach((example, idx) => {
      lines.push(`${idx + 1}. ${example}`);
    });
    lines.push("");
  }

  // Remove trailing newline — join handles it
  return lines.join("\n");
}

/**
 * Escape a TOML string value (double-quoted).
 */
function tomlString(value: string): string {
  // Escape backslashes and double quotes
  const escaped = value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  return `"${escaped}"`;
}

/**
 * Serialize a primitive TOML value.
 */
function tomlValue(value: string | number | boolean): string {
  if (typeof value === "string") return tomlString(value);
  if (typeof value === "number") return String(value);
  if (typeof value === "boolean") return value ? "true" : "false";
  return tomlString(String(value));
}

/**
 * Generate a TOML config file from a CodexTomlConfig (no external dependencies).
 */
export function generateToml(config: CodexTomlConfig): string {
  const lines: string[] = [];

  // [agent] section
  lines.push("[agent]");
  lines.push(`name = ${tomlString(config.agent.name)}`);
  lines.push(`model = ${tomlString(config.agent.model)}`);
  lines.push(`max_turns = ${config.agent.max_turns}`);
  lines.push("");

  // [[tools]] array of tables
  for (const tool of config.tools) {
    lines.push("[[tools]]");
    lines.push(`name = ${tomlString(tool.name)}`);
    lines.push(`enabled = ${tomlValue(tool.enabled)}`);
    lines.push("");
  }

  // [[skills]] array of tables
  for (const skill of config.skills) {
    lines.push("[[skills]]");
    lines.push(`name = ${tomlString(skill.name)}`);
    lines.push("");
  }

  // [safety] section
  lines.push("[safety]");
  lines.push(`autonomy = ${tomlString(config.safety.autonomy)}`);

  // require_approval_for as an inline TOML array of strings
  const approvalItems = config.safety.require_approval_for
    .map((item) => tomlString(item))
    .join(", ");
  lines.push(`require_approval_for = [${approvalItems}]`);

  return lines.join("\n");
}
