import {afterEach,expect,it,vi} from 'vitest';
import {mkdtempSync,readFileSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {createHash} from 'node:crypto';
import {CompanyOsService,verifyCompanyOsBundle} from '../core/company-os';
import {fetchCompanyOsUpdate,companyOsTar} from '../core/company-os-updates';
const cleanup:Array<()=>void>=[];afterEach(()=>cleanup.splice(0).forEach(fn=>fn()));
const digest=(v:string|Buffer)=>createHash('sha256').update(v).digest('hex');
function fixture(){const dir=mkdtempSync(join(tmpdir(),'company-os-'));const path=resolve('third_party/company-os/bundle.json'),release=JSON.parse(readFileSync('third_party/company-os/manifest.json','utf8'));const fetcher=vi.fn();const service=new CompanyOsService(dir,path,release,fetcher);cleanup.push(()=>{service.close();rmSync(dir,{recursive:true,force:true});});return {dir,path,release,service,fetcher};}
it('loads actual pinned framework, disabled by default and scoped by profile',()=>{const f=fixture();expect(f.service.status('owner')).toMatchObject({enabled:false,version:'0.6.0',latest:{state:'not_checked'},schedulingEnabled:false});expect(()=>f.service.context('owner')).toThrow('disabled');f.service.setEnabled('owner',true);const context=f.service.context('owner');expect(context.content).toContain('# Company OS');expect(context.content).toContain('authority');expect(context.bytes).toBeLessThanOrEqual(24000);expect(f.service.status('other').enabled).toBe(false);expect(f.fetcher).not.toHaveBeenCalled();});
it('refuses script context and oversized instructions',()=>{const f=fixture();f.service.setEnabled('p',true);expect(()=>f.service.context('p',{skill:'company-os/company-os/scripts/a.py'})).toThrow();expect(()=>f.service.context('p',{maxBytes:1024})).toThrow('budget');expect(f.service.catalog('p').length).toBeGreaterThan(20);});
it('verifies every bundled source file and rejects changed bytes',()=>{const f=fixture();expect(verifyCompanyOsBundle(f.path,f.release).files).toHaveLength(688);const path=join(f.dir,'bad.json');writeFileSync(path,readFileSync(f.path)+' ');expect(()=>verifyCompanyOsBundle(path,f.release)).toThrow('integrity');});
it('activates verified data atomically with stale UI refusal and rollback across restart',()=>{const f=fixture(),b=JSON.parse(readFileSync(f.path,'utf8'));b.version='0.6.1';b.revision='1'.repeat(40);const data=JSON.stringify(b),path=join(f.dir,'candidate.json');writeFileSync(path,data);const next={version:b.version,revision:b.revision,sha256:digest(data)};f.service.activateVerified(path,next,f.release.sha256);expect(f.service.status('p').version).toBe('0.6.1');expect(()=>f.service.activateVerified(path,next,f.release.sha256)).toThrow('changed');f.service.close();const reopened=new CompanyOsService(f.dir,f.path,f.release,f.fetcher);try{expect(reopened.status('p').version).toBe('0.6.1');reopened.rollback(next.sha256);expect(reopened.status('p').version).toBe('0.6.0');}finally{reopened.close();}});
it('checks only the pinned registry and preserves active version on invalid metadata',async()=>{const f=fixture();f.fetcher.mockResolvedValue(new Response(JSON.stringify({name:'wrong','dist-tags':{latest:'0.6.1'}})));await expect(f.service.checkUpdates('p')).rejects.toThrow();expect(f.service.status('p')).toMatchObject({version:'0.6.0',latest:{state:'error'}});expect(f.fetcher.mock.calls[0][0]).toBe('https://registry.npmjs.org/@mosnin%2fcompanyos');});
it('truthfully reports current and incompatible releases without fetching archives',async()=>{const f=fixture();f.fetcher.mockResolvedValue(new Response(JSON.stringify({name:'@mosnin/companyos','dist-tags':{latest:'0.6.0'}})));expect(await f.service.checkUpdates('p')).toMatchObject({state:'current'});f.fetcher.mockResolvedValue(new Response(JSON.stringify({name:'@mosnin/companyos','dist-tags':{latest:'1.0.0'}})));expect(await f.service.checkUpdates('p')).toMatchObject({state:'incompatible'});expect(f.fetcher).toHaveBeenCalledTimes(2);});
it('refuses untrusted archive URLs, malformed integrity and cancellation before download',async()=>{const metadata={name:'@mosnin/companyos','dist-tags':{latest:'0.6.1'},versions:{'0.6.1':{name:'@mosnin/companyos',version:'0.6.1',gitHead:'1'.repeat(40),dist:{integrity:'sha512-'+Buffer.alloc(64).toString('base64'),tarball:'https://evil.invalid/archive'}}}};const fetcher=vi.fn(async()=>new Response(JSON.stringify(metadata)));await expect(fetchCompanyOsUpdate('0.6.0',fetcher,new AbortController().signal)).rejects.toThrow('Untrusted');expect(fetcher).toHaveBeenCalledOnce();const f=fixture(),c=new AbortController();c.abort();await expect(f.service.checkUpdates('p',{signal:c.signal})).rejects.toThrow();expect(f.fetcher).not.toHaveBeenCalled();});
it('does not accept malformed gzip archives',()=>{expect(()=>companyOsTar(Buffer.from('not gzip'))).toThrow();});
it('auto-activates only an opted-in verified npm archive and retains rollback',async()=>{
 const {gzipSync}=await import('node:zlib');const f=fixture();const content='# Company OS\nVerified updated guidance.';const entries:Record<string,string>={
 'package/package.json':JSON.stringify({name:'@mosnin/companyos',version:'0.6.1',license:'UNLICENSED'}),
 'package/VERSION':'0.6.1\n',
 'package/distribution-manifest.json':JSON.stringify({distribution_version:'0.6.1',files:[{path:'company-os/company-os/SKILL.md',size:Buffer.byteLength(content),sha256:digest(content)}]}),
 'package/skills/company-os/company-os/SKILL.md':content};
 const chunks:Buffer[]=[];for(const [name,text] of Object.entries(entries)){const b=Buffer.from(text),h=Buffer.alloc(512);h.write(name);h.write('0000644\0',100);h.write(b.length.toString(8).padStart(11,'0')+'\0',124);h.fill(32,148,156);h.write('0',156);const sum=h.reduce((a,b)=>a+b,0);h.write(sum.toString(8).padStart(6,'0')+'\0 ',148);chunks.push(h,b,Buffer.alloc((512-b.length%512)%512));}chunks.push(Buffer.alloc(1024));const archive=gzipSync(Buffer.concat(chunks));
 const metadata={name:'@mosnin/companyos','dist-tags':{latest:'0.6.1'},versions:{'0.6.1':{name:'@mosnin/companyos',version:'0.6.1',gitHead:'1'.repeat(40),dist:{integrity:'sha512-'+createHash('sha512').update(archive).digest('base64'),tarball:'https://registry.npmjs.org/@mosnin/companyos/-/companyos-0.6.1.tgz'}}}};
 f.fetcher.mockImplementation(async(url:string)=>new Response(url.endsWith('.tgz')?archive:JSON.stringify(metadata)));
 expect(await f.service.checkUpdates('p')).toMatchObject({state:'available'});expect(f.service.status('p').version).toBe('0.6.0');
 f.service.setAutoUpdate('p',true);expect(await f.service.checkUpdates('p')).toMatchObject({state:'updated'});const current=f.service.status('p');expect(current.version).toBe('0.6.1');expect(current.rollbackAvailable).toBe(true);f.service.rollback(current.sha256);expect(f.service.status('p').version).toBe('0.6.0');
});
