import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { mkdtempSync, writeFileSync, readFileSync, rmSync, existsSync, mkdirSync, symlinkSync, realpathSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { execFileSync, spawn } from 'node:child_process';
import { HelmService } from '../core/helm-service.js';
import { helmArgs, helmProviderError, helmAgentEnv } from '../core/helm-adapters.js';
let dir:string,root:string,service:HelmService;
const git=(...args:string[])=>execFileSync('git',args,{cwd:root,stdio:'pipe'}).toString();
async function settled(id:string){for(let n=0;n<300;n++){const r=service.get(id);if(!['starting','running'].includes(r.status))return r;await new Promise(r=>setTimeout(r,10));}throw Error('Run did not settle');}
function fake(code:string){const p=join(dir,'fake');writeFileSync(p,`#!${process.execPath}\n${code}`,{mode:0o700});return p;}
function setup(code:string){service=new HelmService(join(dir,'data'),()=>{}, {env:{...process.env,HADES_HELM_CODEX_BIN:fake(code)}});}
beforeEach(()=>{dir=mkdtempSync(join(tmpdir(),'helm-test-'));root=join(dir,'repo');execFileSync('git',['init',root],{stdio:'pipe'});git('config','user.email','test@example.test');git('config','user.name','Test');writeFileSync(join(root,'a.txt'),'base');git('add','.');git('commit','-m','base');});
afterEach(async()=>{if(service){await Promise.all(service.list().map(r=>service.cancel(r.id).catch(()=>{})));service.close();}rmSync(dir,{recursive:true,force:true});});
describe('Helm lifecycle',()=>{
 it('isolates HEAD, retains changed and untracked evidence, verifies exact revision and invalidates stale checks',async()=>{
  setup("require('fs').writeFileSync('a.txt','changed');require('fs').writeFileSync('new.txt','new');console.log('done')");
  writeFileSync(join(root,'a.txt'),'source dirty');
  const started=await service.start({root,agent:'codex',prompt:'fix'});expect(started.status).toBe('starting');
  const run=await settled(started.id);expect(run.status).toBe('needs_review');expect(run.sourceDirty).toBe(true);expect(readFileSync(join(root,'a.txt'),'utf8')).toBe('source dirty');
  const diff=await service.diff(run.id);expect(diff.files).toEqual(expect.arrayContaining(['a.txt','new.txt']));
  const checked=await service.verify(run.id,[{command:process.execPath,args:['-e',"if(require('fs').readFileSync('new.txt','utf8')!=='new')process.exit(1)"]}]);expect(checked.status).toBe('verified');
  writeFileSync(join(run.workspace,'new.txt'),'different');expect((await service.diff(run.id)).stale).toBe(true);expect(service.get(run.id).status).toBe('needs_review');
 });
 it('fails nonzero exit and refuses to upgrade failed provider to verified',async()=>{setup("console.log('bad');process.exit(3)");const r=await settled((await service.start({root,agent:'codex',prompt:'fix'})).id);expect(r.status).toBe('failed');expect(r.exitCode).toBe(3);await expect(service.verify(r.id,[{command:'true',args:[]}])).rejects.toThrow();});
 it('retains structured provider error despite bounded output tail',async()=>{setup("console.log(JSON.stringify({type:'turn.failed',error:{message:'provider failed'}}));console.log('x'.repeat(400000))");const r=await settled((await service.start({root,agent:'codex',prompt:'fix'})).id);expect(r.status).toBe('failed');expect(r.error).toBe('provider failed');expect(r.output.length).toBeLessThanOrEqual(200000);expect(r.outputTruncated).toBe(true);});
 it('cancels a running process and retains workspace',async()=>{setup("setInterval(()=>console.log('working'),20)");const r=await service.start({root,agent:'codex',prompt:'fix'});for(let n=0;n<100&&service.get(r.id).status==='starting';n++)await new Promise(r=>setTimeout(r,10));const cancelled=await service.cancel(r.id);expect(cancelled.status).toBe('cancelled');expect(service.ownsWorkspace(cancelled.workspace)).toBe(true);});
 it('restores persisted active runs as interrupted without replay',async()=>{setup("setInterval(()=>{},1000)");const r=await service.start({root,agent:'codex',prompt:'fix'});for(let n=0;n<100&&service.get(r.id).status==='starting';n++)await new Promise(r=>setTimeout(r,10));const persisted=readFileSync(join(dir,'data/helm/runs.json'),'utf8');await service.cancel(r.id);service.close();writeFileSync(join(dir,'data/helm/runs.json'),persisted);service=new HelmService(join(dir,'data'),()=>{});expect(service.get(r.id).status).toBe('interrupted');});
 it('fails timed out execution and limits concurrent preparation',async()=>{setup("setInterval(()=>{},1000)");const runs=await Promise.all(Array.from({length:4},()=>service.start({root,agent:'codex',prompt:'fix',maxMinutes:0.01})));await expect(service.start({root,agent:'codex',prompt:'fifth'})).rejects.toThrow('four');expect((await settled(runs[0].id)).error).toContain('time limit');await Promise.all(runs.map(r=>service.cancel(r.id)));});
 it('does not verify when check mutates the revision or fails',async()=>{setup("console.log('done')");const r=await settled((await service.start({root,agent:'codex',prompt:'fix'})).id);const verified=await service.verify(r.id,[{command:process.execPath,args:['-e',"require('fs').writeFileSync('a.txt','mutated')"]}]);expect(verified.status).toBe('needs_review');expect(verified.error).toContain('changed');const failed=await service.verify(r.id,[{command:process.execPath,args:['-e','process.exit(1)']}]);expect(failed.checks?.[0].passed).toBe(false);});
 it('does not execute inherited checkout hooks',async()=>{const marker=join(dir,'hook-ran');writeFileSync(join(root,'.git/hooks/post-checkout'),`#!/bin/sh\ntouch '${marker}'`,{mode:0o700});setup("console.log('done')");await settled((await service.start({root,agent:'codex',prompt:'fix'})).id);expect(existsSync(marker)).toBe(false);});
 it('shares one time allocation across agent and automatic checks',async()=>{setup("setTimeout(()=>console.log('done'),350)");const r=await settled((await service.start({root,agent:'codex',prompt:'fix',maxMinutes:0.01,checks:[{command:process.execPath,args:['-e','setTimeout(()=>{},500)']}]})).id);expect(r.status).toBe('failed');expect(r.error).toContain('time limit');});
 it('preserves cancellation during final verification snapshot',async()=>{setup("console.log('done')");const r=await settled((await service.start({root,agent:'codex',prompt:'fix'})).id);const original=(service as any).snapshot.bind(service);let snapshots=0;let cancellation:Promise<unknown>|undefined;(service as any).snapshot=async(...args:unknown[])=>{const result=await original(...args);if(++snapshots===2)cancellation=service.cancel(r.id);return result;};const result=await service.verify(r.id,[{command:process.execPath,args:['-e','process.exit(0)']}]);await cancellation;expect(result.status).toBe('cancelled');});
 it.skipIf(process.platform==='win32')('kills process descendants after a hard host crash',async()=>{
  const childPid=join(dir,'child.pid');const descendantPid=join(dir,'descendant.pid');
  const binary=fake(`const fs=require('fs');fs.writeFileSync(${JSON.stringify(childPid)},String(process.pid));const c=require('child_process').spawn(process.execPath,['-e',"process.on('SIGTERM',()=>{});setInterval(()=>{},1000)"],{stdio:'ignore'});fs.writeFileSync(${JSON.stringify(descendantPid)},String(c.pid));setInterval(()=>{},1000)`);
  const host=join(dir,'host.mts');writeFileSync(host,`import {HelmService} from ${JSON.stringify(resolve('src/desktop/core/helm-service.ts'))};const s=new HelmService(${JSON.stringify(join(dir,'crash-data'))},()=>{},{env:{...process.env,HADES_HELM_CODEX_BIN:${JSON.stringify(binary)}}});await s.start({root:${JSON.stringify(root)},agent:'codex',prompt:'wait'});setInterval(()=>{},1000);`);
  const processHost=spawn(process.execPath,['--import',resolve('node_modules/tsx/dist/loader.mjs'),host],{stdio:'ignore'});
  try {
   for(let n=0;n<300&&!existsSync(descendantPid);n++)await new Promise(r=>setTimeout(r,10));expect(existsSync(descendantPid)).toBe(true);
   const pids=[Number(readFileSync(childPid,'utf8')),Number(readFileSync(descendantPid,'utf8'))];
   processHost.kill('SIGKILL');await new Promise<void>(r=>processHost.once('close',()=>r()));
   const alive=(pid:number)=>{try{return !execFileSync('ps',['-o','stat=','-p',String(pid)],{stdio:['ignore','pipe','ignore']}).toString().trim().startsWith('Z');}catch{return false;}};
   for(let n=0;n<200&&pids.some(alive);n++)await new Promise(r=>setTimeout(r,10));expect(pids.some(alive)).toBe(false);
  }finally{processHost.kill('SIGKILL');}
 });
 it('settles built-in automatic check timeout instead of leaving running without a process',async()=>{service=new HelmService(join(dir,'data'),()=>{}, {runBuiltin:async()=>({output:'done'})});const r=await settled((await service.start({root,agent:'hades',prompt:'fix',maxMinutes:0.02,checks:[{command:process.execPath,args:['-e','setTimeout(()=>{},3000)']}]})).id);expect(r.status).toBe('failed');expect(r.error).toContain('time limit');expect(service.hasActiveWork()).toBe(false);});
 it('coalesces and caches version discovery until explicit refresh',async()=>{const counter=join(dir,'count');const binary=fake(`const fs=require('fs');let n=0;try{n=Number(fs.readFileSync(${JSON.stringify(counter)},'utf8'))}catch{}fs.writeFileSync(${JSON.stringify(counter)},String(n+1));console.log('test 1.0')`);service=new HelmService(join(dir,'data'),()=>{}, {env:{...process.env,HADES_HELM_CODEX_BIN:binary,HADES_HELM_CLAUDE_BIN:'/missing',HADES_HELM_GEMINI_BIN:'/missing',HADES_HELM_GROK_BIN:'/missing',HADES_HELM_OPENCODE_BIN:'/missing'}});await Promise.all([service.agents(),service.agents(),service.agents()]);await service.agents();expect(readFileSync(counter,'utf8')).toBe('1');const refreshed=await service.agents(true);expect(readFileSync(counter,'utf8')).toBe('3');expect(refreshed.find(a=>a.id==='codex')?.readiness?.model).toBe('unverified');await service.agents();expect(readFileSync(counter,'utf8')).toBe('3');});
 it('stops provider output safely when atomic storage fails',async()=>{setup("setInterval(()=>console.log('working'),50)");const r=await service.start({root,agent:'codex',prompt:'fix'});for(let n=0;n<100&&!service.get(r.id).output;n++)await new Promise(r=>setTimeout(r,10));const file=join(dir,'data/helm/runs.json');rmSync(file);mkdirSync(file);const failed=await settled(r.id);expect(failed.status).toBe('failed');expect(failed.error).toContain('persist');});
 it('canonicalizes data directory aliases without granting rebound workspace authority',async()=>{const alias=join(dir,'alias');symlinkSync(dir,alias);service=new HelmService(join(alias,'data'),()=>{}, {runBuiltin:async()=>({output:'done'})});const r=await settled((await service.start({root,agent:'hades',prompt:'fix'})).id);expect(r.workspace).toBe(realpathSync(r.workspace));expect(service.ownsWorkspace(realpathSync(r.workspace))).toBe(true);const moved=join(dir,'other');mkdirSync(moved);rmSync(r.workspace,{recursive:true});symlinkSync(moved,r.workspace);expect(service.ownsWorkspace(r.workspace)).toBe(false);});
 it('binds CLI cwd, PWD, INIT_CWD and explicit OpenCode directory to the isolated workspace',async()=>{const binary=fake("const fs=require('fs');const args=process.argv.slice(2);if(process.env.PWD!==process.cwd()||process.env.INIT_CWD!==process.cwd()||args[args.indexOf('--dir')+1]!==process.cwd()||process.env.OPENCODE_ATTACH_URL)process.exit(7);fs.writeFileSync('bound.txt',process.cwd())");service=new HelmService(join(dir,'data'),()=>{}, {env:{...process.env,PWD:root,INIT_CWD:root,HADES_HELM_OPENCODE_BIN:binary,OPENCODE_ATTACH_URL:'http://unused.invalid'}});const r=await settled((await service.start({root,agent:'opencode',prompt:'fix'})).id);expect(r.status).toBe('needs_review');expect(readFileSync(join(r.workspace,'bound.txt'),'utf8')).toBe(r.workspace);expect(existsSync(join(root,'bound.txt'))).toBe(false);});
 it('reports a Git access timeout without claiming provider failure',async()=>{setup("console.log('done')");const original=(service as any).process.bind(service);(service as any).process=(command:string,...args:unknown[])=>command==='git'?Promise.resolve({code:null,output:'',truncated:false,error:'Task time limit reached'}):original(command,...args);const r=await settled((await service.start({root,agent:'codex',prompt:'fix'})).id);expect(r.status).toBe('failed');expect(r.baseSha).toBe('');expect(r.error).toContain('Git repository access timed out');});
 it('binds built-in session before completion',async()=>{service=new HelmService(join(dir,'data'),()=>{}, {runBuiltin:async(_,signal,update)=>{update({sessionId:'session-1',output:'working'});await new Promise<void>(resolve=>signal.addEventListener('abort',()=>resolve(),{once:true}));return {output:'stopped'};}});const r=await service.start({root,agent:'hades',prompt:'fix'});for(let n=0;n<100&&!service.get(r.id).sessionId;n++)await new Promise(r=>setTimeout(r,10));expect(service.get(r.id).sessionId).toBe('session-1');expect((await service.cancel(r.id)).status).toBe('cancelled');});
});
it('parses pretty JSON failure and keeps prompts separate from flags',()=>{expect(helmProviderError(JSON.stringify({is_error:true,result:'denied'},null,2))).toBe('denied');for(const agent of ['codex','claude'] as const){const args=helmArgs(agent,'--help');expect(args.at(-2)).toBe('--');}expect(helmArgs('grok','task')).not.toContain('--always-approve');});

it('uses Hades managed Codex keyring without overriding standalone auth and reports nested errors',()=>{const env={...process.env,HADES_CODEX_HOME:'/managed',OPENAI_API_KEY:'test',CODEX_API_KEY:'test',CODEX_ACCESS_TOKEN:'test'};expect(helmAgentEnv('codex',env)).not.toHaveProperty('OPENAI_API_KEY');expect(helmArgs('codex','task',undefined,true)).toContain('cli_auth_credentials_store="keyring"');expect(helmArgs('codex','task')).not.toContain('cli_auth_credentials_store="keyring"');expect(helmAgentEnv('codex',{NODE_ENV:'test',OPENAI_API_KEY:'test'}).OPENAI_API_KEY).toBe('test');expect(helmProviderError(JSON.stringify({error:{data:{message:'Model unavailable',headers:{secret:'redacted'}}}}))).toBe('Model unavailable');});
