import { describe,expect,it,vi } from 'vitest';
import { createHash,randomUUID } from 'node:crypto';
import { helmOrcaTools,type HelmOrcaToolInput,type HelmOrcaToolScope } from '../core/helm-orca-tools';
function fixture(){const controller=new AbortController();const reservations=new Map<string,{id:string;hash:string}>();const scope:HelmOrcaToolScope={signal:controller.signal,guard:vi.fn(),canStart:true,readiness:vi.fn(()=>({state:'unavailable'})),preflight:vi.fn(),reserve:vi.fn((input:HelmOrcaToolInput)=>{const hash=createHash('sha256').update(JSON.stringify(input)).digest('hex');const old=reservations.get(input.key);if(old){if(old.hash!==hash)throw new Error('key conflict');return old.id;}if(reservations.size>=4)throw new Error('four allocations');const id=randomUUID();reservations.set(input.key,{id,hash});return id;}),owns:id=>[...reservations.values()].some(r=>r.id===id),start:vi.fn(async(id)=>({id,state:'ready'})),status:vi.fn(async()=>({state:'unknown'})),read:vi.fn(async()=>({output:'bounded'})),reconcile:vi.fn(async()=>({state:'unknown'})),stop:vi.fn(async()=>({state:'unknown'}))};const run=(name:string,input:unknown)=>helmOrcaTools(scope).find(t=>t.name===name)!.run(JSON.stringify(input));return {scope,controller,reservations,run};}
const input={key:'fix-login',prompt:'Fix fixture',agent:'codex'};
describe('conversation Orca authority boundary',()=>{
 it('reuses durable caller identity across reconstructed tools',async()=>{const f=fixture();await f.run('helm_orca_start',input);await f.run('helm_orca_start',input);expect(f.reservations.size).toBe(1);expect(vi.mocked(f.scope.start).mock.calls[0][0]).toBe(vi.mocked(f.scope.start).mock.calls[1][0]);});
 it('refuses malformed authority fields and different payload for same key',async()=>{const f=fixture();expect((await f.run('helm_orca_start',{...input,root:'/elsewhere'})).ok).toBe(false);expect(f.scope.preflight).not.toHaveBeenCalled();await f.run('helm_orca_start',input);expect((await f.run('helm_orca_start',{...input,prompt:'other'})).ok).toBe(false);expect(f.scope.start).toHaveBeenCalledTimes(1);});
 it('preflight refusal and lease revocation allocate nothing',async()=>{const f=fixture();f.scope.preflight=()=>{throw new Error('no artifact');};expect((await f.run('helm_orca_start',input)).ok).toBe(false);expect(f.reservations.size).toBe(0);f.scope.preflight=async()=>{f.controller.abort();};expect((await f.run('helm_orca_start',input)).ok).toBe(false);expect(f.reservations.size).toBe(0);});
 it('lost return retains request allocation and never refunds cap',async()=>{const f=fixture();f.scope.start=vi.fn(async()=>{throw new Error('unknown');});for(let n=0;n<4;n++)expect((await f.run('helm_orca_start',{...input,key:'key'+n})).ok).toBe(false);expect((await f.run('helm_orca_start',{...input,key:'fifth'})).ok).toBe(false);expect(f.scope.start).toHaveBeenCalledTimes(4);expect(f.reservations.size).toBe(4);});
 it('all task operations refuse a foreign task before service calls',async()=>{const f=fixture();for(const name of ['status','read','reconcile','stop'])expect((await f.run('helm_orca_'+name,{id:randomUUID()})).ok).toBe(false);for(const method of ['status','read','reconcile','stop'] as const)expect(f.scope[method]).not.toHaveBeenCalled();});
 it('child scope has no start and cap limitations are explicit',()=>{const f=fixture();f.scope.canStart=false;expect(helmOrcaTools(f.scope).some(t=>t.name==='helm_orca_start')).toBe(false);expect(helmOrcaTools(f.scope)[0].description).toContain('not enforced');});
 it('guard is rechecked after async status response',async()=>{const f=fixture();await f.run('helm_orca_start',input);const id=[...f.reservations.values()][0].id;f.scope.status=async()=>{f.controller.abort();return {state:'ready'};};expect((await f.run('helm_orca_status',{id})).ok).toBe(false);});
});
