import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,mkdirSync,writeFileSync,rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { execFileSync } from 'node:child_process';
import { sourceState,uiFiles,sha256,verifyHelm,runtimePayloadSha256 } from '../helm-provenance.mjs';
function fixture(){const root=mkdtempSync(join(tmpdir(),'helm-proof-')),source=join(root,'source'),assets=join(root,'ui'),runtime=join(root,'runtime');mkdirSync(source);mkdirSync(assets);writeFileSync(join(source,'brand.ts'),'Helm');const git=args=>execFileSync('git',['-C',source,...args],{stdio:'pipe'});git(['init']);git(['add','.']);git(['-c','user.name=Fixture','-c','user.email=fixture@invalid','-c','core.hooksPath=/dev/null','commit','-m','fixture']);writeFileSync(join(assets,'index.html'),'<title>Helm</title>');writeFileSync(runtime,'runtime');const state=sourceState(source),pin={revision:state.revision,version:'1.18.21',bun:'1.3.14'},proof={schema:2,...state,version:pin.version,bun:pin.bun,uiFiles:uiFiles(assets),runtimeSha256:sha256(runtime)};const save=()=>writeFileSync(join(assets,'helm-provenance.json'),JSON.stringify(proof));save();return {root,source,assets,runtime,pin,proof,save,close:()=>rmSync(root,{recursive:true,force:true})};}
test('clean exact source/assets/runtime validates',()=>{const f=fixture();try{assert.equal(verifyHelm(f).revision,f.pin.revision);}finally{f.close();}});
for(const [label,mutate] of [['legacy schema',f=>{delete f.proof.schema;f.save();}],['dirty source',f=>writeFileSync(join(f.source,'brand.ts'),'OpenCode')],['untracked source',f=>writeFileSync(join(f.source,'new.ts'),'changed')],['changed UI bytes',f=>writeFileSync(join(f.assets,'index.html'),'stale')],['extra UI asset',f=>writeFileSync(join(f.assets,'extra.js'),'extra')],['runtime mismatch',f=>writeFileSync(f.runtime,'other')],['wrong Bun',f=>{f.proof.bun='other';f.save();}],['dirty provenance',f=>{f.proof.dirty=true;f.save();}]])test('rejects '+label,()=>{const f=fixture();try{mutate(f);assert.throws(()=>verifyHelm(f),/Helm|source|runtime/);}finally{f.close();}});

test('offline artifact verification needs no source checkout',()=>{const f=fixture();try{rmSync(f.source,{recursive:true,force:true});assert.equal(verifyHelm({...f,source:undefined}).revision,f.pin.revision);}finally{f.close();}});

test('signing normalization permits signature data changes but rejects code changes',()=>{const f=fixture();try{const binary=Buffer.alloc(32+16+16+4);binary.writeUInt32LE(0xfeedfacf,0);binary.writeUInt32LE(1,16);binary.writeUInt32LE(16,20);binary.writeUInt32LE(0x1d,32);binary.writeUInt32LE(16,36);binary.writeUInt32LE(64,40);binary.writeUInt32LE(4,44);writeFileSync(f.runtime,binary);const original=runtimePayloadSha256(f.runtime);binary[65]=1;writeFileSync(f.runtime,binary);assert.equal(runtimePayloadSha256(f.runtime),original);binary[55]=1;writeFileSync(f.runtime,binary);assert.notEqual(runtimePayloadSha256(f.runtime),original);}finally{f.close();}});
