import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtempSync, realpathSync, writeFileSync, readFileSync, rmSync, mkdirSync, symlinkSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { stageOrcaPackage, validateOrcaPackage } from './package-helm-orca.mjs';
function fixture(){const root=realpathSync(mkdtempSync(join(tmpdir(),'orca-pack-'))),source=join(root,'source');mkdirSync(source);const files=['orcad.js','daemon-entry.js','parcel-watcher-process-entry.js'].map(path=>{writeFileSync(join(source,path),'fixture');return {path,bytes:7,sha256:createHash('sha256').update('fixture').digest('hex')};});const manifest={sourceRevision:'bf4e2705046cf9ef9c915929a9646da85717af07',platform:process.platform,arch:process.arch,files};const save=()=>writeFileSync(join(source,'helm-orca-build.json'),JSON.stringify(manifest));save();return {root,source,manifest,save,close:()=>rmSync(root,{recursive:true,force:true})};}
test('stages exact tree beside node and removes stale prior files',()=>{const f=fixture();try{const dest=join(f.root,'Resources','helm-orca');mkdirSync(dest,{recursive:true});writeFileSync(join(dest,'stale.js'),'stale');stageOrcaPackage(f.source,dest);assert.equal(existsSync(join(dest,'stale.js')),false);assert.deepEqual(validateOrcaPackage(dest),validateOrcaPackage(f.source));}finally{f.close();}});
for(const bad of ['hash','pin','platform','arch','traversal','symlink','extra','missing'])test('rejects '+bad+' preserving prior output',()=>{const f=fixture();try{const dest=join(f.root,'out');mkdirSync(dest);writeFileSync(join(dest,'prior'),'prior');if(bad==='hash')writeFileSync(join(f.source,'orcad.js'),'changed');if(bad==='pin')f.manifest.sourceRevision='bad';if(bad==='platform')f.manifest.platform='wrong';if(bad==='arch')f.manifest.arch='wrong';if(bad==='traversal')f.manifest.files[0].path='../escape';if(bad==='symlink'){rmSync(join(f.source,'orcad.js'));symlinkSync('daemon-entry.js',join(f.source,'orcad.js'));}if(bad==='extra')writeFileSync(join(f.source,'stale'),'extra');if(bad==='missing')rmSync(join(f.source,'orcad.js'));f.save();assert.throws(()=>stageOrcaPackage(f.source,dest));assert.equal(readFileSync(join(dest,'prior'),'utf8'),'prior');}finally{f.close();}});
test('both production packaging paths include preflight and installed resource path',()=>{const config=JSON.parse(readFileSync(new URL('../src-tauri/tauri.conf.json',import.meta.url),'utf8'));assert.equal(config.bundle.resources['../dist/helm-orca/'],'helm-orca/');assert.match(config.build.beforeBuildCommand,/package-helm-orca.mjs --check/);const script=readFileSync(new URL('../script/build_and_run.sh',import.meta.url),'utf8');assert.match(script,/--stage dist\/helm-orca "\$APP\/Contents\/Resources\/helm-orca"/);assert.match(script,/--check "\$APP\/Contents\/Resources\/helm-orca"/);});
